[phases.setup]
nixPkgs = ['nodejs-18_x', 'chromium']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['echo "No build step required"']

[start]
cmd = 'node index.js'

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'
PUPPETEER_EXECUTABLE_PATH = '/nix/store/*-chromium-*/bin/chromium'
